### ISSUE TITLE
Support more gates in Yao

### ISSUE THREAD

**Issue by GiggleLiu** [Sov-trotter/IBMQ-Julia#1]
1. transform YaoBlocks to basic form, so that the `RepeatBlock` et. al will be translated to equivalent elementary form that containing only `chain`, `put` and primitive blocks.
https://github.com/QuantumBFS/YaoPlots.jl/blob/7a68da39aae2d92bb26d2d636c8da6cb46703b3a/src/vizcircuit.jl#L171

This will make the circuit much easier to handle.

2. Better error handling for not supported gates.

**Comment by Sov-trotter** [comment]
Closing it here. Let's discuss in the main package issues :)
